// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'Run FlutterFire CLI with the Firebase project owned by this app.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'Run FlutterFire CLI with the Firebase project owned by this app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'Run FlutterFire CLI with the Firebase project owned by this app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeX2ynEOQDy-0-DCMt5BkjTn1Dzfm7Opg',
    appId: '1:86299609726:web:d52e164088db455eeb262f',
    messagingSenderId: '86299609726',
    projectId: 'dompet-digital-13b1b',
    authDomain: 'dompet-digital-13b1b.firebaseapp.com',
    storageBucket: 'dompet-digital-13b1b.firebasestorage.app',
    measurementId: 'G-089HN7PVZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVT9I-iHP5-kVgmHLoIqcXTY4nHG14Y3Y',
    appId: '1:86299609726:android:76457edca8fcc9a5eb262f',
    messagingSenderId: '86299609726',
    projectId: 'dompet-digital-13b1b',
    storageBucket: 'dompet-digital-13b1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0I2KNCxZP3YnlKUmLf_ZHeJB_IGO45E',
    appId: '1:86299609726:ios:b22a05ef006f423eeb262f',
    messagingSenderId: '86299609726',
    projectId: 'dompet-digital-13b1b',
    storageBucket: 'dompet-digital-13b1b.firebasestorage.app',
    iosBundleId: 'com.example.pasarMalam',
  );
}
